# SPDX-FileCopyrightText: 2024 The JMP.boot Developers
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "jmp_boot_target_uefi"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
uefi = { version = "0.30.0", features = ["logger", "panic_handler"] }
